name = "cf-note"
main = "src/index.js"
compatibility_date = "2026-02-15"

[[rules]]
type = "Data"
globs = ["**/*.ico"]
fallthrough = false

[[d1_databases]]
binding = "DB"
database_name = "cf-note-sql"
database_id = "af988028-13af-4fb6-ad0e-3abc65979c79"
